### ISSUE TITLE
app.js and app.css is not being generated.

### ISSUE THREAD

**Issue by shahidkarimi** [InfyOmLabs/laravel-generator#1057]
Fresh Laravel 9 installation with InfyOmLabs generator
app.js and app.css not being generated.

Followed all these stuff: https://infyom.com/open-source/laravelgenerator/docs/9.0/publish-layout

What's wrong?

**Comment by CrunchyArtie** [comment]
I'm not sur if your problem is same as mine. But with a fresh laravel 9 installation I do have a problem with app.js and app.css. It was because the generated views use mix, but by default a new laravel 9 project use vite. So I replace every app.js and app.css call with something like `@vite(['resources/css/app.css'])`

**Comment by Mosaab-Emam** [comment]
Same issue here. However @CrunchyArtie's solution works.

I will submit a PR with a fix, even though this project seems semi-abandoned of late.

**Comment by mitulgolakiya** [comment]
We have added a vite support and I think it is fixed now. Check now and feel free to re-open the issue if you are still facing an issue.
