### ISSUE TITLE
tinyInteger gets casts as boolean

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#134]
I noticed that when creating scaffolding from a table, my fields that use tinyInteger are represented as boolean in the generated model.. which causes integers (2 and above) to be misrepresented in the table as just "true"

**Comment by mitulgolakiya** [comment]
This is a default behavior because the doctrine is mapping `tinyint` as `boolean`. Maybe you can change it your own way.

https://github.com/doctrine/dbal/blob/090066c7e186a26a248344140a10ffb78a8f4186/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L637

https://stackoverflow.com/questions/14681197/incorrect-mapping-of-mysql-tinyint2-as-boolean-with-doctrine

I know, its a very old issue and a far late reply. But I've just started reviewing all old issues and closing them.

**Comment by vesper8** [comment]
can I just say @mitulgolakiya that I'm very happy to see you back and hard at work on this project! this one is really very useful!
