### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by digitaldreams** [InfyOmLabs/laravel-generator#139]
Its a waste of time trying to installing this library. 
Its have a very poor documentation and i followed all of their installation guide but it fails.

**Comment by tpharaoh** [comment]
It certainly has a learning curve... biggest misunderstanding could be
related to templates... once you got that... you can install it. I have
uesd it several times.

Of course, there are other packages if one of them fits your needs better.
This certainly has its strengths...

**Comment by digitaldreams** [comment]
You should add a video which will highlight most of the main features. So developer will be able to decide is this package will helpful or not before wasting their valuable time. 
Please add a video tutorial on your hope page.

**Comment by digitaldreams** [comment]
If you are a pure laravel developer then you should follow laravel documentation. Its simple, descriptive and moreover no confusion.

**Comment by phillipmadsen** [comment]
He is still building this that is why it is unstable dev build. why would he make a video on something he is not sure of? He would be wasting his time. You should wait for the stable package or use his old one.

Just  a thought.

**Comment by mitulgolakiya** [comment]
Dear @digitaldreams, Not sure what not worked on your side. Because lots of developers are already using it on a daily basis. And this package got more than 5K downloads till date and more than 500 stars and it's still growing. Not sure why you seems it's a waste of time.

Also, we are already here to help everyone if anyone is getting any issue.

so just let us know what's not working on your side rather than telling it "WASTE OF TIME". Don't take it personally, but I don't think these 500 Stargazers had wasted their time.

Also about your video question, we already have it in a queue. [Here](https://github.com/InfyOmLabs/laravel-generator/issues/118) you can find an issue for it.

But as @phillipmadsen said, we are continuously making it more stable and more rich with features. so once everything is stabilized we will create videos for various features.

so just post the issue that you have.

**Comment by john5db** [comment]
@digitaldreams it is not waste of time. You can learn this package in less time than you could build single CRUD resource controller manually.

But once you learn this package you can create fully working CRUD in less than minute.It will save your tons of time and money. So investing on learning is never waste of time.

Yes this package docs are bit confusing, There should be quick start guide with all commands in single page. You can refer old docs for referance https://github.com/mitulgolakiya/laravel-api-generator/blob/master/installation.md


I hope you will like this package once you learn it.

**Comment by mitulgolakiya** [comment]
@digitaldreams Closing this issue. Open a new issue with specific details, if you need anything.
