### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#150]
Is there a artisan command or a way to update the published config file if it changes upon package update?

Anyone have an idea on this. 

At least a way to notify user that they need to manually update the config due to changes or new options?

Just wondering

**Comment by mitulgolakiya** [comment]
I would say, if any new things are introduced then it should be mentioned in release notes and upgrade guide. As of now, we are having a blog where we are mentioning new upgraded stuff. so it's fine.

Publishing a new file is not a good idea, because it can overwrite your existing configuration file.
