### ISSUE TITLE
Datatable Not Working - Clean Install

### ISSUE THREAD

**Issue by tjimenez** [InfyOmLabs/laravel-generator#257]
When a scaffold is generated all views works perfectly except the index. 
It happends with a clean install. 

If you try with an existing boilerplate eg: [bootstrap](https://github.com/InfyOmLabs/bootstrap-generator), works correctly. If you want to add new composer packages after running "composer update" stop working again.

Very nice work you have done guys! I hope you can find a soon solution to this issue.

**Comment by tjimenez** [comment]
Solved @mitulgolakiya seems like the something was missing in the template. 
@yield('scripts')

**Comment by folkevil** [comment]
i got same problem, @tjimenez which is template file need to fix ?

**Comment by tjimenez** [comment]
@folkevil you may be working in an existing project or a custom template, if so, just paste @yield('scripts') in the footer after all inclusion JS files.

I'm not sure but I think this instruction is not documented, that's why it works in the boilerplates but not in a custom or existing project.

**Comment by underdpt** [comment]
I think this is related to #230. 
In my case, the template I'm using (Josh Template, based on AdminLTE) names the script section as 'footer_scripts' instead of 'scripts'. I added the @yield('scripts') command after the @yield('footer_scripts') on views\admin\layouts\default.blade.php to make it work.

Maybe there should be an option for setting the scripts section name?

**Comment by mitulgolakiya** [comment]
@tjimenez great to it's working.
@underdpt will consider in future to specify section name.
