### ISSUE TITLE
Can i use it in laravel 5.3

### ISSUE THREAD

**Issue by Its-rahulG** [InfyOmLabs/laravel-generator#258]
Hi, i'm currently working on laravel 5.3, because taylor said that coding part is done only the documentation part is left. becuase laravel 5.3 is so cool and even more better then 5.2 i'm creating my new project API with it. Since laravel 5.3 routes dir has changed  can i still make use of this awesome library, ?

**Comment by motia** [comment]
In laravel 5.3, there is 4 changes that affect enjoying laravel-generator directly:
 
 1. the App\Http\routes.php file is replaced by routes\web.php and routes\api.php
 2. route names are not affected by group prefixes so using api_scaffold will result in duplicate names for resources so scaffolding will not work right.
 3. Both of AuthController and PasswordController are split on two, so the auth routes generated by the package are obsolete for laravel 5.3.
 4. Logout accepts a POST method parameterized by a _token instead of a blank GET method.

However, using this package is still possible. 
First of all, install your composer dependecies (use larevel-collective 5.3 instead of 5.2).
Then add the required service providers as the documentation suggests.

 Then run:

    php artisan vendor:publish
Now let's adapt the package to the laravel upgrades.

 1.  in config/laravel_generator modify the attributes inside the path array

        'routes'            => app_path('../routes/web.php'),

        'api_routes'        => app_path('../routes/api_v1.php'),
        
	then create the file **api_v1.php** inside the **routes** directory

 2. copy the code below to routes/api.php

	    Route::group(['prefix' => 'v1', 'namespace' => 'API', 'as' => 'api.v1.'], function () {
	        require config('infyom.laravel_generator.path.api_routes');
	    });

	Now, run the following command but make sure you say **no** to the prompt about adding an api group because we already created it manually
	
	    php artisan infyom:publish
	
	**Note:** in App\providers\RouteServiceProvider, you will find a function ***mapApiRoutes***. Remove the ***auth:api*** from the middleware array within the function body unless you need it.

 3.  Add the line below to **web.php**

	    Auth::routes();
	    Route::get('/home', 'HomeController@index');

 4.  Or by calling (overwrite what you want but dont accept adding standard roots)

    php artisan infyom.publish:layout
    
	replace the lines 93 and 94 from **app.blade.php** by

	    <a href="{{ url('/logout') }}" 
		    onclick="event.preventDefault();
		    document.getElementById('logout-form').submit();">Logout</a>
	    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;"> {{ csrf_field() }} 
	    </form>
You can also replace steps 3 and 4 by `php artisan make:auth`. But you will not have the generator sidebar.

**Comment by mitulgolakiya** [comment]
@Its-rahulG No, it's currently not supported with laravel 5.3. Right now I'm working on specifying relationships. Once that's done it will be on a plan as a next thing.

**Comment by mitulgolakiya** [comment]
@motia Thanks for pointing out required changes. It will be really helpful.

**Comment by mitulgolakiya** [comment]
@Its-rahulG @motia 5.3 support is now available.

**Comment by hengsoheak** [comment]
Database Transaction is not work

   try {

                DB::beginTransaction();
                $cats = new Cat();
                $res = [];
                $cats->parent_id = $this->request->input('category_id');
                $cats->status = ($this->request->input('status')) ? $this->request->input('status') : 0;
                if ($res['cat'] = $cats->save()) {

                    $catD = new CategoryDescriptions();
                    $catD->category_id = $cats->id;
                    $catD->language_id = 1;
                    $catD->name = $this->request->input('en_name');
                    if ($res['cat2'] = $catD->save()) {
                        $catD2 = new CategoryDescriptions();
                        $catD2->category_id = $cats->id;
                        $catD2->language_id = 2;
                        $catD2->name = $this->request->input('kh_name');
                        $res['all'] = $catD2->save();
                    }
                }
                if(!empty($res['all'])) {
                    //DB::commit();
                    return $res;
                }
            } catch (Exception $e) {
                DB::rollback();
            }
