### ISSUE TITLE
Not Using

### ISSUE THREAD

**Issue by it9xpro** [InfyOmLabs/laravel-generator#260]
full tutorial 
![screenshot_1](https://cloud.githubusercontent.com/assets/6617916/17725042/adc6fd34-6471-11e6-8ad2-e939bf6d2219.png)

**Comment by it9xpro** [comment]
Command "infyom.publish:generator-builder" is not defined.      [39;49m
[37;41m  Did you mean one of these?                                      [39;49m
[37;41m      infyom.publish:layout                                       [39;49m
[37;41m      infyom.publish:templates

**Comment by mitulgolakiya** [comment]
This was a documentation problem. It's fixed now.

And I think you are trying to use generator-builder without including that package. so you need to add that.

But I will recommend you to use it from command line, because generator-builder is in beta and not in sync with some latest features of generator.
