### ISSUE TITLE
DataTables: send Request to the builder()

### ISSUE THREAD

**Issue by krugerdavid** [InfyOmLabs/laravel-generator#290]
Hi Guys

Is there a way to send parameters for the Builder? I'm using infyom and it comes with this great library. Was able to create a great collection with multiple joins. But I'm working on a report table, which I must send parameters for the filters. But right now I'm unable to set those parameters using the PHP classes itself and not the javascript code. Please let me know if there is an alternative or solution for this.

Regards

**Comment by lemmellem** [comment]
Hi, im new to infyom + datatables, "was able to create a great collection with multiple joins" i need to do this also, but i can't seem to make it work. TIA!

**Comment by mitulgolakiya** [comment]
@krugerdavid @lemmellem too late reply, But maybe it can help someone. I think the best place to do this is a `query` method in your `ModelDatatable.php` since that's what filters the records. so better you inject `Request` there, check for param and build a query that you want based on your filter params.
