### ISSUE TITLE
Managin relationships

### ISSUE THREAD

**Issue by gabrieldasilva** [InfyOmLabs/laravel-generator#312]
Hi everyone!

I'm trying to do something and I want to know what is the best way.

I have two tables: categories and category_translations. The relationship is one to many. A category has many category_translations. 

When I run the generator with scaffold option for both tables i'm obtaining a complete CRUD. I want to have a create form for the category where I could add directly the translations to be stored on category_translations table. This makes me store the translation info in the store method from CateogryRepository

What's the way to do this? Calling the CategoryTranslation model into CatagoryRepository is a bad practice?

**Comment by mitulgolakiya** [comment]
@gabrieldasilva can you post a complete schema here ? then we can have better idea. Because if category translations are always added from Category then I think you don't need a separate CRUD at all.

But if you have one translation in more than one category then you need a CRUD.

Also, you can directly attach or save translations via relationship. I don't think you should call translation repository into category repository. Even you call, I don't think its a bad practice, as long as that function is called from various places. By that way, you can avoid code redundancy.
