### ISSUE TITLE
Using relationships

### ISSUE THREAD

**Issue by showFocus** [InfyOmLabs/laravel-generator#337]
I have a News and NewsCategories models which I have generated CRUD for using the relationship option.

I now need to generate a select list for the News model to select the NewsCategory it belongs to.

I know how to do this in the model but no idea how to do it using the repository pattern.

I can't see any examples in the docs so any help with this would be appreciated.

Thanks

**Comment by Mohamed-Elwan** [comment]
you are right  but it's a about [l5-repository](https://github.com/andersao/l5-repository) there's no such a thing like pluck or list. so we've to mention that to them not here I think

**Comment by perezale** [comment]
This is getting old but I've seen l5-repository documentation and the query has to be built like this:

`api/resourceA**?with=resourceB**`

This is the case of a 1-N relationship

This works when requesting a list of resourceA and could work when selecting an item (`api/resourceA/1?with=resourceB`) but the generated API Controller show() method needs some changes as follows:

```
public function show(Request $request, $id) //Added $request param
    {
        $this->fileRepository->pushCriteria(new RequestCriteria($request)); //Added RequestCriteria
        ....
```

That's it! That worked but I didnt run any tests. I believe this change should by added to the apicontroler template.

**Comment by mitulgolakiya** [comment]
@perezale that can be the solution. But still not sure what and how it needs to be displayed in the table. so can not comment much. But I think it's too old and maybe some solution is already developed then. so closing it.

Even from laravel 5.8, we have a base repository published and no more dependent on l5-repository, since it not active for a long time and planning to add our customizations there.
