### ISSUE TITLE
ErrorException in BaseRepository.php line 57: array_search() expects parameter 2 to be array, string given

### ISSUE THREAD

**Issue by underdpt** [InfyOmLabs/laravel-generator#346]
Hi,

I'm trying to update a User model, which has a relation to a Role model. The relation is defined as: 
```php
    public function roles()
    {
        return $this->belongsToMany(static::$rolesModel, 'role_users', 'user_id', 'role_id')->withTimestamps();
    }
```
When updating a model, it throws the error:
```
ErrorException in BaseRepository.php line 57: array_search() expects parameter 2 to be array, string given
```
This is trying to manage Cartalyst/Sentinel users and roles with scaffolding generated by laravel-generator.

**Comment by pyrello** [comment]
The code in question is expecting an array of values along the lines of:
```php
$user = [
    // ...
    'roles' => [
        0 => 2,
        1 => 3,
        2 => 6,
    ],
    // ...
];
```

The roles key corresponds to an array of role ids that are going to be sync'ed with the user. My guess is that if you look at the input values from the request, you are returning only a single value for roles and that is because your html form inputs that allow the user to select the roles use `id=roles` instead of `id=roles[]`. In the first instance the roles value is returned back to the server as `roles = 'x'`. If multiple values are selected, only the last one will be passed through since the others will be considered duplicates. In the second instance the roles value is returned as `roles = ['x']` or `roles = ['x', 'y', 'z']` if multiple values are selected.

**Comment by underdpt** [comment]
Hi @pyrello 
What a newie mistake! It works now that i've modified the input to be an array.
Just for anyone landing here, you should change the `name` attribute of the input, not the `id` (which may not exist).
