### ISSUE TITLE
Add fields to existing scaffold

### ISSUE THREAD

**Issue by n6ither** [InfyOmLabs/laravel-generator#376]
Hi, I couldn't find any clue in the docs regarding this. 
I used, for example, artisan **infyom:scaffold Member (name, dob, address, phone)** and after a couple of days I realized that I need a new field, what is the correct way to proceed here? A rollback? Do I need to edit every file to include the new field?
Thank you for your time, sorry if I'm asking something stupid.

**Comment by phillipmadsen** [comment]
There is an easy way to do this already. I build my cruds out before I generate them, then I use the fields_file.json generate the crud from the file. As a developer, this is very handy because like you have found you might or almost always need to edit or add to the crud. This way if I add a new field all I need to do is re-crud it with the same command. 

I take is a step further and create a script to run through all the commands on a install command for easy replication of the project. 

Anyway, just my thoughts, just trying to help. This way you don't need to edit core files or wait for changes to accomplish the same thing.
