### ISSUE TITLE
app.stub directory issue

### ISSUE THREAD

**Issue by amin101** [InfyOmLabs/laravel-generator#389]
error when running : 

`php artisan infyom.publish:layout`

` [ErrorException]                                                                                                                                      
  copy(C:\xampp\htdocs\sherkat\vendor/infyomlabs/core-templates/templates/scaffold/layouts/app.stub): failed to open stream: No such file or directory`

there is no `core-template` directory

**Comment by amin101** [comment]
found out that `"infyomlabs/core-templates": "5.3.x-dev"` should be added to composer.json

**Comment by mitulgolakiya** [comment]
@amin101 core-templates are no longer maintained. You should try to use adminlte-templates.

**Comment by amin101** [comment]
so maybe you should fix `php artisan infyom.publish:layout` running code as it requires `core-templates` .

**Comment by lucas-quinn-guru** [comment]
Change config. Replace 'teplates' parameter from 'core-templates' to 'adminlte-templates' in laravel_generator.php config. Default parameter have a deprecated value.

Since the core-templates is no longer maintained, I wonder why it is still the default of the infyomlabs config.  The default should be adminlte-templates.  Or fix the install.
