### ISSUE TITLE
Scaffolding to use data from other tables

### ISSUE THREAD

**Issue by nexxai** [InfyOmLabs/laravel-generator#395]
This is probably an extremely stupid question, but I'm still kinda new at this so go easy on me.

Let's say I have two tables "Productions" and "Tours" with the corresponding models and relationships all working fine and correct.  The Productions table has 2 columns: ID and Title.  The Tours table has a column called "production_id" which references the ID column in the Productions table, and it has its own ID as well as its own Title column.

The relationships go: a production has many tours and a tour has one production.  I've used the `php artisan infyom:scaffold $MODEL_NAME --fromTable --tableName=$TABLE_NAME` commands to create the necessary repositories, etc.  

When I go to the "tours/create" admin page, how would I get it to populate the "Production" field so that while it would *show* the title of the production on the web interface, in the background it's using the production's ID number and will let me save the new Tour?

**Comment by xaviersand** [comment]
I was also looking for that feature but i still could not find the documentation how to manage the foreign keys.
For now, it is only generatic a "number" field, instead of a select (id+description)

**Comment by reiter777** [comment]
you cant, but you can create de production_id in the sccafold, and put a select as @xaviersand  said in your controller $productions = Production::::orderBy('nameOrwhatEver')->pluck('nameOrwhatEver', 'id'); and then in your controller inclued the select  {!! Form::select('productions',$productions , null, ['class' => 'form-control']) !!} have a nice day man

**Comment by kleytonroan** [comment]
I liked what @reiter777 said, on my crete function in the TourController:
- add **$productions = Production::orderBy('name')->pluck('name', 'id');**
- add "$productions" variable to the view **return view('production.create.blade.php')->with(['productions', $productions])**, or use compact(), you decide it

On the fields.blade.php, on the Tour directory:
- add **{!! Form::select('production_id', $productions , null, ['class' => 'form-control']) !!}**

That's it, in index view, to bring the production's name, i did some changes, I don´t use ->eloquent($this->query()) anymore, i changed to ->of($tour) and i did a leftjoin on production table to bring the production.name as prodution_name, then I added "prodution_name" on columns method.

I don't know if that's the best way, or have a lot of best ways to do that, i don't found anything on web, than i read the documentation and did my changes.

I'm brazilian, I hope that my english is understandable

**Comment by reiter777** [comment]
@kleytonroan thats not the best way man, but it works, it depends at what do you need for your project and what protections you also need to implement.

**Comment by kleytonroan** [comment]
@reiter777, using a Blog Example, I have my User Model e my Post Model
I did the relationship using hasMany Post to User, and belongsTo User to Post, but in my index view, I want display user.name, intead user_id, this is my "problem".

doing some tests, I figured out another way:
in PostDataTable.php

`
public function query() {
    $posts= Post::with('User');
    return $this->applyScopes($posts);
}
`

and in the getColumns function, I use dotNotation in data:

```
private function getColumns() {
    return [
        //Other Columns
        'user_name' => ['name' => 'user_name', 'data' => 'user.name'],
    ];
}
```

But using QueryLog(), i saw that laravel make 2 selects for this
1 - select in post
2 - select users where id in a collection of users

because i used ::('with') i think, in the other way, return only 1 select, doing left join

I can't upload a image, give the error (Something went really wrong, and we can’t process that file.)

here is a link to the queryLog Print https://drive.google.com/open?id=0B9TTtADfdtRkSy1TbnJ4Y1lYd0k

**Comment by reiter777** [comment]
@kleytonroan you dont need to do de second way man, only with the relations you can access any data of the 2 models, maybe i can help you via skype, here is my user reiter7771 feel free to add me man.

**Comment by kikoseijo** [comment]
Did you find a solution, im stuck at same point, 😭

**Comment by mitulgolakiya** [comment]
Added new option `selectTable`.
Read docs here: http://labs.infyom.com/laravelgenerator/docs/6.0/fields-input-guide

**Comment by adnoh** [comment]
@mitulgolakiya is this feature removed again? I have several informations on that topic (accessing a relation table) and found a few links to the docs in specific format like you mention (6.0) - but in the current docs on the website this informations are all gone.

**Comment by mitulgolakiya** [comment]
@adnoh can you please mention which information you are referring to? Because I think there are no changes in the docs website. 

I can get that added if needed.

**Comment by adnoh** [comment]
@mitulgolakiya sure: if you try to access http://labs.infyom.com/laravelgenerator/docs/6.0/fields-input-guide you're getting redirected to docs where no information about selectTable for example is mentioned. So I guess this information was getting lost somehow. This field is golden if you're working with relationships so it should be really good described - maybe with a working example - because a lot of people will be wondering how to get this into their frontend easily.
I'm quite new to the generator - so maybe I get things wrong.
I've also seen in older commits there where features which I'm really looking for - like checkbox group - and later removed again - I know different topic - but really strange to me - maybe it was not on purpose to get rid of them again :-)

**Comment by yagnesh987** [comment]
> Added new option `selectTable`. Read docs here: http://labs.infyom.com/laravelgenerator/docs/6.0/fields-input-guide

It's not working in version ^6.0
