### ISSUE TITLE
Composer update

### ISSUE THREAD

**Issue by stefanrakic** [InfyOmLabs/laravel-generator#396]
I try composer update on two my projects: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravelcollective/html dev-master requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev].
    - laravelcollective/html dev-master requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev].
    - Conclusion: don't install illuminate/view 5.5.x-dev
    - Installation request for laravelcollective/html dev-master -> satisfiable by laravelcollective/html[dev-master].

**Comment by whereisjefe** [comment]
That is because your composer.json has `laravelcollective/html` set to `dev-master` which for that project is for laravel 5.5.x-dev. Depending on your version of Laravel you are running you should change it to 
`5.4.x-dev`
`5.3.x-dev`

Take a look at https://packagist.org/packages/laravelcollective/html for their versions

**Comment by mitulgolakiya** [comment]
@stefanrakic yes, as @whereisjefe said, laravel collective should be used based on your laravel version.
