### ISSUE TITLE
Create permissions

### ISSUE THREAD

**Issue by Silvio12** [InfyOmLabs/laravel-generator#478]
Is it possible to add a function to create permissions with a model as well?
Like create-offer, edit-offer, destroy-offer... in the permissions table?

**Comment by mitulgolakiya** [comment]
@Silvio12 this package is not intended to generate permissions or any other stuff. Rather than that, it's focusing on api and scaffold generator.

But of course, you can publish its templates and customize it to generator whatever stuff you need. You can add your custom methods to the model file and generate permissions.

You can find docs [here](http://labs.infyom.com/laravelgenerator/docs/5.5/publish-templates).

**Comment by Silvio12** [comment]
Hi, I believe That's is a missunderstanding. I have already an Permission package.
I just want to add the migration file for it.
But I don't get a migration file when I crate my model and views from an database table.
For example i have an user table and i want to create the User model, views and so on. Than i want to add 5 new lines in my permissions table link "create-user", "edit-user", "destroy-user", "index-user",
