### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by DylandeWit** [InfyOmLabs/laravel-generator#481]
Are there any plans on releasing a version 1.0?

**Comment by mitulgolakiya** [comment]
Yes, there is a plan, but I want to stabilize it first. We don't have test cases for it now and when we introduce some fixes or new features, I'm not sure, it will break something else or not.

And that's the another reason, this package is making a slow progress because once I merge some pull request or add something new, I need to test each and everything.

so I have a plan to cover at least 70% code with test coverage, then would plan for the release versions.

but yeah, that already in the queue :)
