### ISSUE TITLE
Lean infyom:api

### ISSUE THREAD

**Issue by chriscalip** [InfyOmLabs/laravel-generator#484]
So I am checking in on package to generate api just to save up some work. I noticed workflow of laravel-generator does not make use laravel fractal transformer called Resources. Also it is now asking to be use in every api route .. adding in overhead.

```
php artisan infyom:api Term --fieldsFile=scaffolds/fields_term.json
    new file:   app/Http/Controllers/API/TermAPIController.php
    new file:   app/Http/Requests/API/CreateTermAPIRequest.php
    new file:   app/Http/Requests/API/UpdateTermAPIRequest.php
    new file:   app/Models/Term.php
    new file:   app/Repositories/TermRepository.php
    new file:   database/migrations/2017_09_20_012156_create_terms_table.php
    modified:   routes/api.php
    new file:   tests/TermApiTest.php
    new file:   tests/TermRepositoryTest.php
    new file:   tests/traits/MakeTermTrait.php
```

My proposal is a lean option for 
```
php artisan infyom:api Term --fieldsFile=scaffolds/fields_term.json --lean
    new file:   app/Http/Controllers/TermAPIController.php
    new file:   app/Http/Requests/CreateTermAPIRequest.php
    new file:   app/Http/Requests/UpdateTermAPIRequest.php
    new file:   app/Models/Term.php
    new file:   app/Repositories/TermRepository.php
    new file:   database/migrations/2017_09_20_012156_create_terms_table.php
    modified:   routes/api.php
    new file:   tests/TermApiTest.php
    new file:   tests/TermRepositoryTest.php
    new file:   tests/traits/MakeTermTrait.php
```
And Inside these controllers to make use of laravel 5.5 core. eg. Resources as a replacement to fractal transformer. Thus minimize contributed package usage for api calls.

**Comment by chriscalip** [comment]
Repository is good practice, should not be taken out.

**Comment by chriscalip** [comment]
config/laravel_generator.php handles API directory structure.

**Comment by mitulgolakiya** [comment]
@chriscalip it's a good practice when you are just generating APIs. but when we are generating both CRUD and APIs, then maybe I want my API controllers to be in separate folders. and with a separate namespace, which will organize it in the better folder structure.

That's why it extracted into a separate folder. And if you are using APIs only, then you can always change a config and make it your own way. That's why that configuration is provided.

I will keep `lean` option for future release on my list. But as of now I will keep it simple and make it configurable via `config/laravel_generator.php`.
