### ISSUE TITLE
Publish Bug

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#49]
## php artisan infyom.publish:templates

Does not publish common template files. So common stubs are not being added to view folder.

Recap of stubs not publishing

1.  ***views directory*** 
(also gnerator throws error because its looking for table.stub and you have them named table.blade.stub and same thing with the other view)
2.  ***common directory***

**Comment by mitulgolakiya** [comment]
@phillipmadsen I am not able to get table.stub and table.blade.stub thing. Can you describe it bit more ?
Also I have added a support for copy views directory.

You mean common directory by the directory contains `errors.blade.php` and `paginate.blade.php` ?

If yes, then why you need to publish that folder ? Because even it will not reflect the changes, because those are loaded as views from static directory of `core-templates` over [here](https://github.com/InfyOmLabs/core-templates/blob/master/src/CoreTemplatesServiceProvider.php#L16).

If you want to use your own errors and paginate then you should create it in your views directory and then customize templates to you those views.
