### ISSUE TITLE
 separate tasks depending on roles / Relationships

### ISSUE THREAD

**Issue by 33sKamal** [InfyOmLabs/laravel-generator#576]
1 -> How to separate tasks depending on roles so let's say i have Admin/Student ...
2 -> What if i have Task ( Books ) and i have to give the related Author (Select ) How to do this 
Tnaks

**Comment by mitulgolakiya** [comment]
@33sKamal I would say, this issue is more of the logical stuff. The intention of this package is to help in setting up CRUD and to save time in redundant work. The aim of this package is not to provide any functionality related to Roles. I think you can post a question to somewhere else. Stackoverflow etc.
