### ISSUE TITLE
php artisan infyom:scaffold $controller --fromTable --tableName=$table - fails if table has geom fields

### ISSUE THREAD

**Issue by baradhili** [InfyOmLabs/laravel-generator#593]
Tried this on an existing app, but it failed due to a Point field in the table.. is there a way to tell it to ignore certain fields? I don't want that in the crud anyway :)

**Comment by mitulgolakiya** [comment]
@baradhili --fromTable is fully compatible only with MySQL db. as we are using `doctrine/dbal`.

**Comment by baradhili** [comment]
Bit quick to close there... yes Mysqldb support "Point" and a whole raft of geom types.. RTM :)

**Comment by mitulgolakiya** [comment]
@baradhili I agree. I can check if I can implement support like that. Re-opening for a reference.

**Comment by baradhili** [comment]
I think better - could we simply allow an argument for something like "--exclude-fields="? supporting geom functions is tough and database specific..

**Comment by mitulgolakiya** [comment]
yes, and just FYI, that will not be even added to anywhere. Model, Searchable fields or etc. It will be just like they do not exist in the table.

**Comment by baradhili** [comment]
well any dev working with mysql geom types is probably capable of adding it themselves :) You can't make everyone happy :)

**Comment by mitulgolakiya** [comment]
@baradhili support to ignore certain fields added.
You can read docs [here](http://labs.infyom.com/laravelgenerator/docs/5.8/generator-options#ignore-fields).

Also, I've added support to specify custom mappings on doctrine, because an exception is thrown inside the doctrine package, so there is no way to ignore it.
So, to get it to work, you need to specify custom doctrine mappings into `config/infyom/laravel_generator.php`. docs [here](http://gen-docs.com/docs/develop/configuration#from-table) and then use ignore option.
