### ISSUE TITLE
Events generated twice

### ISSUE THREAD

**Issue by henriquerdd** [InfyOmLabs/laravel-generator#665]
I'm currently using infyom-generator 5.7.x-dev version with laravel  5.7.

Problem: 

Events related to model 'creating', 'created', 'updating' and 'updated' are being generated twice, once by \InfyOm\Generator\Common\BaseRepository and another by it's parent class \Prettus\Repository\Eloquent\BaseRepository.

This happens because both classes update and create methods invoke the model's save method.

**Comment by perezale** [comment]
Hi, I've seen this behavior too!
I'd really like to fix this.

An example of the problem is [here](https://github.com/InfyOmLabs/laravel-generator/blob/2dc3d4d62f735e3216fcda242f70c9e073154312/src/Common/BaseRepository.php#L37). This is the update case firing saving/save/etc events twice.

There you'll see double calls to update and save, each firing model events.

I think one of those, either update or save calls should be in a withoutEvents callback or handle this by using unsetEventDispatcher. This is not what withoutEvents is intended but can be a solution.

Another option is not doing double save (update/save), but I'm not involved with infyom code enough to make changes.

**Comment by vishalinfyom** [comment]
@perezale update events are firing only once at [here](https://github.com/InfyOmLabs/laravel-generator/blob/2dc3d4d62f735e3216fcda242f70c9e073154312/src/Common/BaseRepository.php#L37), 
 while `$model->save()` no events are fired.

You can use our latest version with laravel 5.8 in which we are publishing `BaseRepository` into application.
