### ISSUE TITLE
multi word scaffold name

### ISSUE THREAD

**Issue by collinsNick** [InfyOmLabs/laravel-generator#777]
my apppologies if this is a noob issue, but when i run the below script:

php artisan infyom:scaffold SomeName --fromTable --tableName=some_name

 everything is generated fine except that the url name comes like this:

Route::resource('SomeName', 'SomeNameController');

currently i have to rename all the routes to be  :  some_name instead of SomeName

is there a way to do this automatically

**Comment by mitulgolakiya** [comment]
@collinsNick I think your routes will be something like this:

`Route::resource('someName', 'SomeNameController');`

in camelCase.

If you want it to be changed to snake_case, then you can use PublishTemplates command as describe here. https://labs.infyom.com/laravelgenerator/docs/6.0/publish-templates

It will publish all the templates in `resources/infyom/infyom-generator-templates` directly. What you need to do since you want to modify routes only. so you should keep only that template file and delete all the other files.
so just keep `scaffold/routes/routes.stub` and delete all other files.

Now modify `scaffold/routes/routes.stub` file with the following content

`Route::resource('$MODEL_NAME_PLURAL_SNAKE$', '$PATH_PREFIX$$MODEL_NAME$Controller');`

And it should work.

**Comment by collinsNick** [comment]
Hi sorry for the late reply, I will give it a go and provide feedback. Thanks for the headsup
