### ISSUE TITLE
After rollback, not all data is deleted

### ISSUE THREAD

**Issue by noxeone** [InfyOmLabs/laravel-generator#851]
After rollback, not all data is deleted

Not deleted: 
migrations, 
information about migrations in DB table "migrations",
DB tables, 
model schemas (/resources/model_schemas/{modelName.json},
in file ViewServiceProvider.php inside the function boot() not deleted relations functions like this: View::composer(['{DB_table_name}.fields'], function ($view) {.....

**Comment by mitulgolakiya** [comment]
@noxeone 

Let me know which version you are using of the generator, because for me it's deleting the migration file, check the below screenshot.

![image](https://user-images.githubusercontent.com/1908535/82412911-18312c80-9a92-11ea-964c-8880448e425f.png)

The model schema file is not deleted purposefully, consider this case, you are generating a scaffold for Doctor. and you made a typo. now what you want to do.

1. You run rollback command
2. It will delete all the files
3. You correct the typo in the model schema file
4. You generate CRUD again from the model schema file, so you don't need to specify fields again.

As long as I know, the generator does not deal with ViewServiceProvider at all. so it does not make any changes while rollback command. Maybe you added that code manually by yourself.

**Comment by noxeone** [comment]
Thanks for the answer!
After updating the generator, migrations files are deleted during rollback.
The rest is clear too

About ViewServiceProvider:
In this file generator registers a request to the table from which data is taken for a related table. It appears after creating a relation.
Example:
Part of the schema from the model Goods:
`{
        "name": "unit_id",
        "dbType": "integer:unsigned:foreign,units,unit_id",
        "htmlType": "selectTable:units:name,unit_id",
	"relation": "mt1,units,unit_id,unit_id",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },`
After creating this model, the following lines appear in the file ViewServiceProvider:
`View::composer(['goods.fields'], function ($view) {
            $unitItems = Unit::pluck('name','unit_id')->toArray();
            $view->with('unitItems', $unitItems);
        });`
And this data is then used to display on the user's screen in UI in template files, like \resources\views\goods\fields.blade.php:
`
<div class="form-group col-sm-6">
    {!! Form::label('unit_id', 'Unit Id:') !!}
    {!! Form::select('unit_id', $unitItems, null, ['class' => 'form-control']) !!}
</div>`

As a result, after the rollback, this data in the file ViewServiceProvider should be deleted
