### ISSUE TITLE
Infyom Generator fails to publish config files, in case of using other ui apart from admin-lte

### ISSUE THREAD

**Issue by muffaddal** [InfyOmLabs/laravel-generator#876]
Hi Guys! Thanks for the awesome package! Really enjoying it. It seems there is a problem while generating basic scaffolding for the core-ui templates. For admin-lte it works fine as it is set to default. But fails for coreui. 

I followed step by step procedure as mentioned in the docs. The base command works properly and publishes the files in the app Directory, but then layout publish fails.

```copy(/var/www/vendor/infyomlabs/adminlte-templates/templates/scaffold/layouts/sidebar.stub): failed to open stream: No such file or directory```

**Comment by mitulgolakiya** [comment]
@muffaddal have you changed the `templates` variable to `coreui-templates` in `config/infyom/laravel_generator.php`?

Because the default config is set to `adminlte-templates`. so if you are using coreui-templates then you need to change the config. That's the expected behavior. 

That's why this is added in the documentation. https://labs.infyom.com/laravelgenerator/docs/7.0/coreui-templates#update-configuration

Hope this helps. Re-open the issue if you need some more help.
