### ISSUE TITLE
Command infyom.publish:templates override customization of infyom-generator-templates

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#888]
When I run command:

`php artisan infyom.publish:templates`

This move all templates/scaffold of my custom theme inside resources/infyom/infyom-generator-templates/scaffold and that is fine.

However, this override all existing customization in infyom-generator-templates/ in my case I lost several change in  infyom-generator-templates/model/model.stub (fortunately I have a copy).

Now I move all my custom .stub of resources/infyom/infyom-generator-templates/ inside my theme folder and need to move this each time I publish template.

Would be good to allow add all .stub in theme so that it can be portable and published per project that need changes of theme.

Or almost avoid to delete customization of resources/infyom/infyom-generator-templates/ stub files.

Thanks

**Comment by mitulgolakiya** [comment]
@thewebartisan7 I am not able to get the issue properly.

`This move all templates/scaffold of my custom theme inside resources/infyom/infyom-generator-templates/scaffold and that is fine.`

This will copy `vendor/infyomlabs/laravel-generator/templates` to `resources/infyom/infyom-generator-templates/scaffold`.

How it will copy your custom theme templates to resources folder?

And when you again publish a command, it does the same again. If you want to run a command again to publish the latest fixes of templates to your theme, of course this will overwrite it and I think it should.

I will suggest you use some VCS like Github or something to track those changes. That will make easy. I don't see any other solution for this.

Can you describe this little bit more? `Would be good to allow add all .stub in theme so that it can be portable and published per project that need changes of theme.`. I'm not sure what do you mean by copy stub file to theme folder?

**Comment by thewebartisan7** [comment]
There are stubs files for theme (views) and there are stubs files for controllers, models, etc. Themes files are separated in package for allow multiple themes, but not controllers, models, etc. 

When I said to allow publish all stubs files, I mean to keep also controllers, models, and other stubs.

Of course I use Git to track changes, we are in 2020 :)

If I remember correctly each times I publish views stubs, then stubs for controllers, models, etc is going overrides, while I expect that only my views stubs are published.

It's passed many times since this issues, and I make a lot of changes on your package, and right now I solve this by keeping all stubs in separated package. I need to setup new installation and test this. 

But as you describe, seem works as designed, so I am not sure if you wish to consider above.

**Comment by ShaileshInfyom** [comment]
@thewebartisan7 Generator stub is fixed like Controller, Model, etc. customization increases the change of issue and stops working if we change or customize controller and model, request, etc. But yes, you can fork and make changes based on your requirement and use it. Thanks for your time!
