### ISSUE TITLE
how to add fields to model and "re"-scaffold ?

### ISSUE THREAD

**Issue by berteh** [InfyOmLabs/laravel-generator#908]
Hello. 
I love your generator tool, thanks a lot for the hard work.

I would like to add a few fields and relations to the current model (eg add some relations on your default  ``User`` model _after_ initial scaffolding: Roles, Picture, Title,...), and have the generated interfaces (admin, crud, api) update accordingly... but the current ``infyom:scaffold`` command does not (seem to) update the current model but creates a new (conflicting) user-create migration instead.

How can I update the models and still have the benefit of your complete scaffolding features ?

thanks !

**Comment by mitulgolakiya** [comment]
Hi @berteh , current that is not a scope of generator to modify the existing models of files. The main goal of this tool is to generate CRUDs and give scaffolding to save the time. so all this stuff needs to be done manually. Because it's really hard to track what was changed and what needs to be skip while creating a new model.
