### ISSUE TITLE
remove external scrips and css

### ISSUE THREAD

**Issue by romanstingler** [InfyOmLabs/laravel-generator#936]
don't use external resources 
include them and load them with laravel mix and call them locally 
```
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://cdn.usebootstrap.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@coreui/coreui@2.1.16/dist/js/coreui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.4.0/perfect-scrollbar.js"></script>
```

**Comment by mitulgolakiya** [comment]
In the very next version we are going to totally remove layout and auth files from laravel generator and instead of that, we will be utilizing laravel fortify. If you quickly want to do that, I will suggest using the https://github.com/InfyOmLabs/laravel-ui-coreui package.
After generating scaffold you may need to generate auth scaffold via https://github.com/InfyOmLabs/laravel-ui-coreui steps and it should replace your existing auth files.

I'm not yet fully sure, it may just work by following the above steps. Maybe some additional steps needed.
