### ISSUE TITLE
DataTable - Add a new (form) action button

### ISSUE THREAD

**Issue by Dri372** [InfyOmLabs/laravel-generator#980]
• It’s easy to add a new action buttun
        ◦ Just add it in the file : resources/views/your_models/datatables_actions.blade.php

    • The only problem is if you add a new « form button » like the « Delete one » the new button will not be aligned with the 3 previous ones. 
To align it your have to add the style « display: inline; » and to do this you have to modify the file :  

        ◦ vendor/laravelcollective/html/src/FormBuilder.php
            ▪ protected $reserved = ['method', 'url', 'route', 'action', 'files', 'style'];
            ▪ and in open function
                • $attributes['style'] = $options['style'] ?? '';

**Comment by mitulgolakiya** [comment]
@Dri372 can you share some screenshots of before style and after style?

**Comment by Dri372** [comment]
Hi @mitulgolakiya 

Of course, thanks for your package.

Before

![before](https://user-images.githubusercontent.com/86223506/132166999-498888e1-ec97-4886-bc7e-af67741e1be9.png)

After

![after](https://user-images.githubusercontent.com/86223506/132167044-59c56d0b-8941-4757-98e5-b55483bde236.png)

**Comment by mitulgolakiya** [comment]
@Dri372 as long as I know, the generator is not adding that button, I think that button is manually added by you. I will say, instead of modifying ` vendor/laravelcollective/html/src/FormBuilder.php`, either you should fix it by writing some global css or you can publish the laravel generator stub files and then do modification there.
