### ISSUE TITLE
Help with foreing keys

### ISSUE THREAD

**Issue by Pilote1989** [InfyOmLabs/laravel-generator#99]
Hi, im trying to generate via json and one field of the model is the following:

```
    {
        "fieldInput": "idPersona:integer",
        "htmlType": "text",
        "validations": "required|exists:users,id",
        "searchable": true,
        "inForm": true,
        "inIndex": true
    },
```

But i get this error : "Invalid argument supplied for foreach()", what im doing wrong?

**Comment by mitulgolakiya** [comment]
Post some more details, because I just did a fresh installation of laravel 5.2 and installed all packages as per documentation. And then copied the existing sample fields file form [here](https://github.com/InfyOmLabs/laravel-generator/blob/master/samples/fields_sample.json) and added this field to that and it worked fine on my machine.

Post some more information of your project or a full JSON file.

**Comment by avescasio** [comment]
I think what is he trying to elaborate is hes trying to create a scaffold with foreign keys that belongs to other tables. I was simulating this on my project too, if not will I make other post for this?

**Comment by mitulgolakiya** [comment]
we have a separate issue for a foreign key and relationship. And I tried with this template and everything is working fine.
so closing it.

**Comment by chungbin1** [comment]
how to create a foreign key on the interface generator_builder???Please

**Comment by mitulgolakiya** [comment]
@chungbin1  we do not have currently support to generate foreign key from generator builder.
